name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]

# cancel running actions for current PR if new commits were pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - name: Check changed files
        run: |
          git update-index -q --refresh
          if ! git diff-index --quiet HEAD --; then
            echo "Some files changed after build:"
            echo
            git diff --stat
            echo
            echo "Please rebuild it locally and commit all the files"
            exit 1
          fi

  check-changelog:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31

      - name: Check if changelog was touched
        run: |
          changelogFound=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | grep -ow "CHANGELOG.md" | wc -w)
          if [ $changelogFound -eq 0 ]; then
            echo '### :boom: Please update the changelog accordingly (https://keepachangelog.com)' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  test-action:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- uses: cardinalby/git-get-release-action@v1
      #  id: get_release
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
      #  with:
      #    latest: true

      - name: Use the license check action on this
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          continueOnBlockedFound: true
          blockedLicenses: |
            GPL
            GPL-2.0
            MIT

